void firstTask();
void secondTask();
void allocation(char* s, char* s0, char symbol);
int strLength(char* str);
void inputStr(char** str);
int checkStrForNull(char* str);
void findWords(char* str, int wordsAmount, int *firstLettersArr, int *lastLettersArr);
void wordForCompare(char* str, int wordsAmount, int *firstLettersArr, int *lastLettersArr, int *repeatsCountArr);
int compareWords(char* str, int firstWordFirstLetter, int firstWordLastLetter, int secondWordFirstLetter, int secondWordLastLetter);
int count_word(char* str);
void inputSymbol(char* a);
int compare(char* s, char* s0, int sWord, int wordsAmountS0, int *firstLettersArrS, int *lastLettersArrS, int *firstLettersArrS0, int *lastLettersArrS0);
int compareTwoWords(char* s, char* s0, int sWord, int s0Word, int *firstLettersArrS, int *lastLettersArrS, int *firstLettersArrS0, int *lastLettersArrS0);
void findWordsForDelete(char* s,char* s0,char symbol,int wordsAmountS,int *firstLettersArrS,int *lastLettersArrS,int wordsAmountS0,int *firstLettersArrS0,int *lastLettersArrS0);
void delete(char* str, int deleteStart, int deleteEnd);
void chooseTask(int *choice);